In [3]:
import pandas as pd
import numpy as np
import persian

In [146]:
df = pd.read_csv('kardan_dataset.csv')
df.head(15)

,ردیف,تاریخ,بازده روزانه صندوق,بازدهی روزانه شاخص,بازدهی سالانه شده صندوق,بازدهی سالانه شده شاخص
0,۱,۱۳۹۹/۱۰/۰۸,۰.۰۵,۱.۲۸,۲۰.۱,"۱۰,۳۷۴.۵۱"
1,۲,۱۳۹۹/۱۰/۰۷,۰.۰۶,(۰.۳۲),۲۳.۱۷,(۶۸.۹۸)
2,۳,۱۳۹۹/۱۰/۰۶,۰.۰۸,(۱.۶۸),۳۲,(۹۹.۷۹)
3,۴,۱۳۹۹/۱۰/۰۵,۰.۰۴,۰,۱۷.۲۵,۰
4,۵,۱۳۹۹/۱۰/۰۴,۰.۰۵,۰,۲۰.۹۴,۰
5,۶,۱۳۹۹/۱۰/۰۳,۰.۰۶,۰.۲,۲۳.۲۷,۱۱۰.۳۳
6,۷,۱۳۹۹/۱۰/۰۲,۰.۰۶,۰.۶,۲۳.۲۹,۷۷۸.۲۷
7,۸,۱۳۹۹/۱۰/۰۱,۰.۰۶,(۰.۱۹),۲۳.۲۵,(۵۰.۰۱)
8,۹,۱۳۹۹/۰۹/۳۰,۰.۰۶,(۰.۴),۲۳.۴۹,(۷۶.۹۷)
9,۱۰,۱۳۹۹/۰۹/۲۹,۰.۰۸,۲.۲۳,۳۳.۳۲,"۳۱۷,۱۰۰.۲۵"
10,۱۱,۱۳۹۹/۰۹/۲۸,۰.۰۵,۰,۱۸.۱۸,۰
11,۱۲,۱۳۹۹/۰۹/۲۷,۰.۰۵,۰,۱۸.۵۳,۰
12,۱۳,۱۳۹۹/۰۹/۲۶,۰.۰۶,(۱.۰۵),۲۴.۵۳,(۹۷.۸۹)
13,۱۴,۱۳۹۹/۰۹/۲۵,۰.۱,(۳.۷۶),۴۵.۳۴,(۱۰۰)
14,۱۵,۱۳۹۹/۰۹/۲۴,۰.۰۱,(۲.۰۸),۵.۰۲,(۹۹.۹۵)

In [147]:
def fa_to_eng(series):
    return series.aggregate(lambda x: persian.convert_fa_numbers(x) if x[0] != '(' else -1*float(persian.convert_fa_numbers(x.strip('()'))))

df['بازده روزانه صندوق'] = fa_to_eng(df['بازده روزانه صندوق'])
df['بازدهی سالانه شده صندوق'] = fa_to_eng(df['بازدهی سالانه شده صندوق'])
df['ردیف'] = fa_to_eng(df['ردیف'])
df['تاریخ'] = fa_to_eng(df['تاریخ'])

df['بازدهی روزانه شاخص'] = fa_to_eng(df['بازدهی روزانه شاخص'])
df['بازدهی سالانه شده شاخص'] = fa_to_eng(df['بازدهی سالانه شده شاخص'])
df.head(20)

,ردیف,تاریخ,بازده روزانه صندوق,بازدهی روزانه شاخص,بازدهی سالانه شده صندوق,بازدهی سالانه شده شاخص
0,1,1399/10/08,0.05,1.28,20.1,"10,374.51"
1,2,1399/10/07,0.06,-0.32,23.17,-68.98
2,3,1399/10/06,0.08,-1.68,32,-99.79
3,4,1399/10/05,0.04,0,17.25,0
4,5,1399/10/04,0.05,0,20.94,0
5,6,1399/10/03,0.06,0.2,23.27,110.33
6,7,1399/10/02,0.06,0.6,23.29,778.27
7,8,1399/10/01,0.06,-0.19,23.25,-50.01
8,9,1399/09/30,0.06,-0.4,23.49,-76.97
9,10,1399/09/29,0.08,2.23,33.32,"317,100.25"
10,11,1399/09/28,0.05,0,18.18,0
11,12,1399/09/27,0.05,0,18.53,0
12,13,1399/09/26,0.06,-1.05,24.53,-97.89
13,14,1399/09/25,0.1,-3.76,45.34,-100
14,15,1399/09/24,0.01,-2.08,5.02,-99.95
15,16,1399/09/23,0.08,-0.77,32.54,-93.95
16,17,1399/09/22,0.04,1.41,17.61,"16,464.2"
17,18,1399/09/21,0.04,0,16.61,0
18,19,1399/09/20,0.04,0,16.87,0

In [148]:
def remove_comma(series):
    return series.str.replace(',', '', regex=False)

df = df.astype(str)
df['بازدهی روزانه شاخص'] = remove_comma(df['بازدهی روزانه شاخص'])
df['بازدهی سالانه شده شاخص'] = remove_comma(df['بازدهی سالانه شده شاخص'])
df['بازده روزانه صندوق'] = remove_comma(df['بازده روزانه صندوق'])
df['بازدهی سالانه شده صندوق'] = remove_comma(df['بازدهی سالانه شده صندوق'])
df[df.columns[2:]] = df[df.columns[2:]].astype('float')
df.head(20)

,ردیف,تاریخ,بازده روزانه صندوق,بازدهی روزانه شاخص,بازدهی سالانه شده صندوق,بازدهی سالانه شده شاخص
0,1,1399/10/08,0.05,1.28,20.10,10374.51
1,2,1399/10/07,0.06,-0.32,23.17,-68.98
2,3,1399/10/06,0.08,-1.68,32.00,-99.79
3,4,1399/10/05,0.04,0.00,17.25,0.00
4,5,1399/10/04,0.05,0.00,20.94,0.00
5,6,1399/10/03,0.06,0.20,23.27,110.33
6,7,1399/10/02,0.06,0.60,23.29,778.27
7,8,1399/10/01,0.06,-0.19,23.25,-50.01
8,9,1399/09/30,0.06,-0.40,23.49,-76.97
9,10,1399/09/29,0.08,2.23,33.32,317100.25
10,11,1399/09/28,0.05,0.00,18.18,0.00
11,12,1399/09/27,0.05,0.00,18.53,0.00
12,13,1399/09/26,0.06,-1.05,24.53,-97.89
13,14,1399/09/25,0.10,-3.76,45.34,-100.00
14,15,1399/09/24,0.01,-2.08,5.02,-99.95
15,16,1399/09/23,0.08,-0.77,32.54,-93.95
16,17,1399/09/22,0.04,1.41,17.61,16464.20
17,18,1399/09/21,0.04,0.00,16.61,0.00
18,19,1399/09/20,0.04,0.00,16.87,0.00